const fs = require('fs');

const products = [
  {
    id: "p1",
    name: "Luxury Baby Set 1",
    name_de: "Luxus Baby Set 1",
    name_fa: "ست لوکس نوزاد 1",
    price: 89,
    image: "/almani/images/IMG_0408.webp",
    images: ["/almani/images/IMG_0408.webp", "/almani/images/IMG_0410.webp"],
    category: "Clothing",
    description: "Premium baby clothing set with high quality materials",
    description_fa: "ست لباس نوزاد پرمیوم با مواد باکیفیت",
    rating: 4.8
  },
  {
    id: "p2",
    name: "Luxury Baby Set 2",
    name_de: "Luxus Baby Set 2",
    name_fa: "ست لوکس نوزاد 2",
    price: 95,
    image: "/almani/images/IMG_0412.webp",
    images: ["/almani/images/IMG_0412.webp", "/almani/images/IMG_0416.webp"],
    category: "Clothing",
    description: "Elegant baby outfit for special occasions",
    description_fa: "لباس نوزاد شیک برای مناسبت های خاص",
    rating: 4.9
  },
  {
    id: "p3",
    name: "Luxury Baby Set 3",
    name_de: "Luxus Baby Set 3",
    name_fa: "ست لوکس نوزاد 3",
    price: 85,
    image: "/almani/images/IMG_0420.webp",
    images: ["/almani/images/IMG_0420.webp", "/almani/images/IMG_0422.webp"],
    category: "Clothing",
    description: "Comfortable and stylish baby clothing",
    description_fa: "لباس نوزاد راحت و شیک",
    rating: 4.7
  },
  {
    id: "p4",
    name: "Luxury Baby Set 4",
    name_de: "Luxus Baby Set 4",
    name_fa: "ست لوکس نوزاد 4",
    price: 92,
    image: "/almani/images/IMG_0426.webp",
    images: ["/almani/images/IMG_0426.webp"],
    category: "Clothing",
    description: "Premium quality baby wear",
    description_fa: "لباس نوزاد با کیفیت پرمیوم",
    rating: 4.8
  },
  {
    id: "p7",
    name: "Herren Anti-Diebstahl-Passwort-Schloss Brusttasche",
    name_de: "Herren Anti-Diebstahl-Passwort-Schloss Brusttasche",
    name_fa: "کیف سینه مردانه ضد سرقت با قفل رمز",
    price: 5.46,
    image: "/almani/images/c (1).avif",
    images: ["/almani/images/c (1).avif", "/almani/images/c (2).avif", "/almani/images/c (3).avif", "/almani/images/c (4).avif", "/almani/images/c (5).avif", "/almani/images/c (6).avif", "/almani/images/c (7).avif"],
    category: "Accessories",
    description: "Hochwertige Anti-Diebstahl-Tasche mit Zahlenschloss, verstellbarem Gurt & mehrlagiger Umhängetasche für Reisen, Pendeln - Kompakte Freihand-Gürteltasche (Schwarz, strapazierfähiges Material). Gratisversand.",
    description_fa: "کیف ضد سرقت با کیفیت بالا با قفل عددی، بند قابل تنظیم و کیف دوشی چند لایه برای سفر و رفت و آمد - کیف کمری فشرده بدون دست (مشکی، مواد بادوام). ارسال رایگان.",
    colors: ["Schwarz", "schwarz mit golden", "grau mit golden", "blau mit golden"],
    colors_fa: ["مشکی", "مشکی با طلایی", "خاکستری با طلایی", "آبی با طلایی"],
    sold: 13000,
    rating: 4.7,
    seller: "Four Seasons Good Products",
    rank: "#5 Am besten bewertet in Herren Schultertaschen",
    shipping: "Gratisversand"
  },
  {
    id: "p9",
    name: "Damen Plüsch-Hausschuhe für drinnen",
    name_de: "Damen Plüsch-Hausschuhe für drinnen",
    name_fa: "دمپایی خانگی پلاشی زنانه",
    price: 6.04,
    image: "/almani/images/d (1).avif",
    images: ["/almani/images/d (1).avif", "/almani/images/d (2).avif", "/almani/images/d (3).avif", "/almani/images/d (4).avif", "/almani/images/d (5).avif", "/almani/images/d (6).avif"],
    category: "Accessories",
    description: "Weicher Stoffobermaterial & Futter, rutschfeste Gummisohle, ganzjährige Wärme, handwaschbare Freizeitschuhe für Zuhause, 4 Farben (Weiß/Schwarz/Rosa/Blau), niedliche Hausschuhe, einfaches Design, strapazierfähiges Traktionssystem. 95% der Kunden sagen, dass der Artikel maßgenau passt.",
    description_fa: "مواد پارچه ای نرم و آستر، کف لاستیکی ضد لغزش، گرمای تمام سال، کفش های آزاد قابل شستشو با دست برای خانه، 4 رنگ (سفید/مشکی/صورتی/آبی)، دمپایی های بامزه، طراحی ساده، سیستم کشش بادوام. 95٪ مشتریان می گویند سایز دقیق است.",
    colors: ["Weiß", "Schwarz", "Khaki", "Pinke Farbe", "Hellgrün"],
    colors_fa: ["سفید", "مشکی", "خاکی", "صورتی", "سبز روشن"],
    sold: 6100,
    rating: 4.9,
    seller: "AYDAPENG",
    rank: "#8 Bestseller",
    originalPrice: 8.77,
    fit: "95% der Kunden sagen, dass der Artikel maßgenau passt"
  },
  {
    id: "p11",
    name: "16-in-1 Gemüseschneider manueller Küchenhelfer",
    name_de: "16-in-1 Gemüseschneider manueller Küchenhelfer",
    name_fa: "خرد کن سبزیجات 16 در 1 دستی",
    price: 7.60,
    image: "/almani/images/e (1).avif",
    images: ["/almani/images/e (1).avif", "/almani/images/e (2).avif", "/almani/images/e (3).avif", "/almani/images/e (4).avif", "/almani/images/e (5).avif", "/almani/images/e (6).avif"],
    category: "Accessories",
    description: "Kommt an in 2+ WERKTAGE - Lokales Lager. 16-in-1 Gemüseschneider mit Abtropfkorb, Handschutz, praktisches Küchengerät für Zwiebeln, Karotten, Knoblauch bequemeres Arbeiten. Modell: ZQ-18. Schnellste Lieferung in 2 Werktage. Sichere Zahlungen.",
    description_fa: "تحویل در 2+ روز کاری - انبار محلی. خرد کن سبزیجات 16 در 1 با سبد آبکش، محافظ دست، وسیله آشپزخانه عملی برای پیاز، هویج، سیر کار راحت تر. مدل: ZQ-18. سریعترین تحویل در 2 روز کاری. پرداخت امن.",
    model: "ZQ-18",
    sold: 15000,
    rating: 4.8,
    seller: "KEEP CHIPER",
    sellerBadge: "Star-Verkäufer",
    rank: "#7 Meistverkaufter Artikel in Küchen-Zubehör",
    shipping: "Standard: 2,99€ oder KOSTENLOS (bei Bestellung von 30,00€+)",
    delivery: "2 Werktage"
  },
  {
    id: "p21",
    name: "360° Drehbarer Make-up Organizer",
    name_de: "360° Drehbarer Make-up Organizer",
    name_fa: "سازمان دهنده آرایش چرخان 360 درجه",
    price: 10.47,
    image: "/almani/images/q (1).avif",
    images: ["/almani/images/q (1).avif", "/almani/images/q (2).avif", "/almani/images/q (3).avif", "/almani/images/q (4).avif", "/almani/images/q (5).avif", "/almani/images/q (6).avif"],
    category: "Accessories",
    description: "Kommt an in 5+ WERKTAGE. 360° Drehbarer Make-up Organizer mit 360-Grad-Drehfuß - Transparente Schminkbox, Kosmetik Organizer mit mehreren Fächern und Make-up Ablage auf der Oberseite, Platzsparender Schminktisch Organizer für Frauen, Keine Montage erforderlich, Elegante Badezimmer- oder Schminktischbox.",
    description_fa: "تحویل در 5+ روز کاری. سازمان دهنده آرایش چرخان 360 درجه با پایه چرخش 360 درجه - جعبه آرایش شفاف، سازمان دهنده لوازم آرایشی با قفسه های متعدد و قفسه آرایش در بالا، سازمان دهنده میز آرایش صرفه جویی در فضا برای زنان، نیازی به مونتاژ ندارد، جعبه حمام یا میز آرایش شیک.",
    color: "Transparent",
    sold: 32,
    rating: 5.0,
    seller: "Lush Kasa",
    shipping: "Kommt an in 5+ WERKTAGE",
    features: ["360-Grad-Drehfuß", "Mehrere Fächer", "Keine Montage erforderlich", "Platzsparend"]
  },
  {
    id: "p23",
    name: "Sechsteiliges Set aus PP-Reißverschluss modischem Reisekoffer",
    name_de: "Sechsteiliges Set aus PP-Reißverschluss modischem Reisekoffer",
    name_fa: "ست شش تکه چمدان مسافرتی مد روز با زیپ PP",
    price: 130.24,
    image: "/almani/images/r (1).avif",
    images: ["/almani/images/r (1).avif", "/almani/images/r (2).avif", "/almani/images/r (3).avif", "/almani/images/r (4).avif", "/almani/images/r (5).avif", "/almani/images/r (6).avif"],
    category: "Accessories",
    description: "Sechsteiliges Set aus PP-Reißverschluss modischem Reisekoffer mit hohem Erscheinungsbild, multifunktionaler Hochbelastbarkeit und universellen Rädern + Reisetasche. 5 ÜBRIG.",
    description_fa: "ست شش تکه چمدان مسافرتی مد روز با زیپ PP با ظاهر بالا، چند منظوره با دوام بالا و چرخ های جهانی + کیف مسافرتی. 5 عدد باقی مانده.",
    colors: ["Schwarzes 13+20+24+28 Zoll Koffer vierteiliges Set + Reisetasche Kosmetiktasche", "Khaki 13+20+24+28 Zoll Koffer 4-teiliges Set + Reisetasche Kosmetiktasche", "Roségold 13+20+24+28 Zoll Koffer-Set mit vier Teilen + Reisetasche Kosmetiktasche", "Hellgraues 13+20+24+28 Zoll Koffer 4-tlg. Set + Reisetasche Kosmetiktasche", "Hellblau 13+20+24+28 Zoll Koffer 4-tlg. Set + Reisetasche Kosmetiktasche", "Dunkelgraues 13+20+24+28 Zoll Koffer 4-teiliges Set + Reisetasche Kosmetiktasche", "Dunkelgrünes 13+20+24+28 Zoll Koffer vierteiliges Set + Reisetasche Kosmetiktasche"],
    colors_fa: ["ست چهار تکه چمدان مشکی 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست 4 تکه چمدان خاکی 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست چهار تکه چمدان رزگلد 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست 4 تکه چمدان خاکستری روشن 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست 4 تکه چمدان آبی روشن 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست 4 تکه چمدان خاکستری تیره 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش", "ست چهار تکه چمدان سبز تیره 13+20+24+28 اینچ + کیف مسافرتی کیف آرایش"],
    sold: 177,
    rating: 4.7,
    seller: "HLD LUGGAGAGE SHOP",
    originalPrice: 181.14,
    stock: 5
  },
  {
    id: "p33",
    name: "Transparenter Kunststoff-Make-up-Organizer mit Schubladen",
    name_de: "Transparenter Kunststoff-Make-up-Organizer mit Schubladen",
    name_fa: "سازمان دهنده آرایش پلاستیکی شفاف با کشو",
    price: 15.67,
    image: "/almani/images/w (1).avif",
    images: ["/almani/images/w (1).avif", "/almani/images/w (2).avif", "/almani/images/w (3).avif", "/almani/images/w (4).avif", "/almani/images/w (5).avif", "/almani/images/w (6).avif"],
    category: "Accessories",
    description: "Eleganter Kosmetik- und Schmuckaufbewahrungs-Lösung für das Badezimmer, Arbeitsplatte, perfekt für Kosmetikprodukte und Zubehör, Make-up-Pinselhalter. Transparenter Kunststoff mit Schubladen.",
    description_fa: "راه حل ذخیره سازی شیک لوازم آرایشی و جواهرات برای حمام، کانتر، عالی برای محصولات آرایشی و لوازم جانبی، نگهدارنده قلم مو آرایش. پلاستیک شفاف با کشو.",
    colors: ["Kosmetik Aufbewahrungsbox Set 2", "Kosmetik-Aufbewahrungsbox Set 5"],
    colors_fa: ["جعبه ذخیره سازی لوازم آرایشی ست 2", "جعبه ذخیره سازی لوازم آرایشی ست 5"],
    sold: 42,
    rating: 5.0,
    seller: "CloudGarb",
    material: "Transparenter Kunststoff"
  },
  {
    id: "p50",
    name: "KABINA YM 82 Vacuum Flask 304 Stainless Steel",
    name_de: "KABINA YM 82 Vakuumflasche aus 304 Edelstahl",
    name_fa: "فلاسک خلاء KABINA YM 82 از استیل 304",
    price: 14.14,
    image: "/almani/images/bo (1).jpg",
    images: ["/almani/images/bo (1).jpg", "/almani/images/bo (2).jpg", "/almani/images/bo (3).jpg", "/almani/images/bo (4).jpg"],
    category: "Accessories",
    description: "Vacuum Flask Made of 304 Stainless Steel, Straw for Children, Elementary School Water with Bottle Lid, 550 ml, Small Dinosaur, Unisex, Youth. Food grade safety: silicone straw made of food grade silicone, 304 stainless steel food grade, safe and non-toxic. One cup for double use: three sets for delivery, lid for water, suction straw, two lifestyles, free to change.",
    description_fa: "فلاسک خلاء از استیل ضد زنگ 304، نی برای کودکان، بطری آب مدرسه با درب، 550 میلی لیتر، دایناسور کوچک، یونیسکس، جوانان. ایمنی درجه غذایی: نی سیلیکونی از سیلیکون درجه غذایی، استیل ضد زنگ 304 درجه غذایی، ایمن و غیر سمی. یک فنجان برای استفاده دوگانه: سه ست برای تحویل، درب برای آب، نی مکش، دو سبک زندگی، آزاد برای تغییر.",
    brand: "kabinga",
    material: "304 Stainless Steel, Silicone",
    color: "Stainlesssteel",
    capacity: "550 Millilitres",
    features: ["Carrying Loop", "Straw", "Food grade safety", "Cotton flake embroidery", "Water resistant material"],
    sold: 1,
    rating: 5.0,
    seller: "kabinga"
  }
];

const content = `export const products = ${JSON.stringify(products, null, 2)}
`;

fs.writeFileSync('pro/components/kokonutui/data.ts', content, 'utf8');
console.log('✅ Data file rebuilt with', products.length, 'products');
